spring.application.name=weather
spring.main.banner-mode=off
server.port=9000

# MCP Server Config
spring.ai.mcp.server.name=my-weather-server
spring.ai.mcp.server.version=0.0.1
spring.ai.mcp.server.request-timeout=1000000

# Hefeng (QWeather) Config
# Use the unique host from your Console -> Settings
hefeng.weather.host=https://kv4nmv277a.re.qweatherapi.com
hefeng.api.key=${WEATHER_API_KEY:}